# Generated by Django 3.2.5 on 2021-07-08 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alldente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='table_number',
        ),
    ]
