# Generated by Django 3.2.5 on 2021-07-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldente', '0002_rename_number_table_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='chairs',
        ),
        migrations.AlterField(
            model_name='table',
            name='category',
            field=models.CharField(choices=[('2pt', '2 seat table'), ('4pt', '4 seat table'), ('8pt', '8 seat table')], max_length=3),
        ),
    ]
