# Generated by Django 3.2.5 on 2021-07-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alldente', '0003_auto_20210708_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='category',
        ),
        migrations.AddField(
            model_name='table',
            name='table_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(default=1),
        ),
    ]
