# Generated by Django 3.2.5 on 2021-07-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alldente', '0004_auto_20210709_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='table_size',
            new_name='table_chairs',
        ),
    ]
