# Generated by Django 3.2.5 on 2021-07-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('2pt', '2 seat table'), ('4pt', '4 seat table'), ('6pt', '6 seat table'), ('8pt', '8 seat table')], max_length=3)),
                ('chairs', models.IntegerField()),
            ],
        ),
    ]
