# Generated by Django 3.2.5 on 2021-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210709_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(choices=[(17.0, '5 pm'), (18.0, '6 pm'), (19.0, '7 pm'), (20.0, '8 pm'), (21.0, '9 pm'), (22.0, '10 pm'), (23.0, '11 pm')]),
        ),
    ]
