# Generated by Django 3.2.5 on 2021-07-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(choices=[('17', '5 pm'), ('18', '6 pm'), ('19', '7 pm'), ('20', '8 pm'), ('21', '9 pm'), ('22', '10 pm'), ('23', '11 pm')]),
        ),
    ]
