# Generated by Django 3.2.5 on 2021-07-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Course',
            new_name='course',
        ),
    ]
