# Generated by Django 3.2.5 on 2021-07-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_rename_course_menu_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='open_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.IntegerField(default=5)),
                ('closing_time', models.IntegerField(default=12)),
                ('book_duration', models.IntegerField(default=2)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(choices=[('---', '----')]),
        ),
    ]
