# Generated by Django 3.2.5 on 2021-07-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20210711_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='available_times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
