# Generated by Django 3.2.5 on 2021-07-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_available_times'),
    ]

    operations = [
        migrations.DeleteModel(
            name='available_times',
        ),
    ]
