# Generated by Django 3.2.5 on 2021-07-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_alter_booking_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='EMPTY', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.IntegerField(default='0000'),
        ),
    ]
