# Generated by Django 3.2.5 on 2021-07-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_auto_20210712_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Booked_for',
            new_name='booked_for',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='Bookholder',
            new_name='bookholder',
        ),
    ]
