# Generated by Django 3.2.5 on 2021-07-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_booking_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='table_number',
            field=models.IntegerField(default='0'),
        ),
    ]
