# Generated by Django 3.2.5 on 2021-07-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_booking_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='book_table',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bookholder',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
    ]
