# Generated by Django 3.2.5 on 2021-07-16 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_auto_20210712_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_email',
            field=models.EmailField(default='none', max_length=256),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, default='0123456789', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table'),
        ),
    ]
