# Generated by Django 3.2.5 on 2021-07-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_auto_20210717_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_email',
            field=models.EmailField(default='Please enter your email please.', max_length=256),
        ),
    ]
