# Generated by Django 3.2.5 on 2021-07-19 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_auto_20210719_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_number',
        ),
    ]
